plugin:
    name: 'martinimultimedia.contact::lang.plugin.name'
    description: 'martinimultimedia.contact::lang.plugin.description'
    author: 'Martini Multimedia'
    icon: oc-icon-envelope
    homepage: ''
navigation:
    contacts:
        label: Contatti
        url: martinimultimedia/contact/contacts
        icon: icon-envelope-o
